
export const SEARCH_USERS = 'SEARCH_USERS';
export const RESET_SEARCH_USERS = 'RESET_SEARCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const RESET_USER = 'RESET_USER';
export const FETCH_USER_REPOS = 'FETCH_USER_REPOS';